all: main

main: graph.cpp graph.h main.cpp Makefile minus.h mymap.cpp mymap.h node.cpp node.h operation.cpp operation.h plus.h
	g++ -std=c++11 main.cpp graph.cpp mymap.cpp node.cpp operation.cpp -o main